export const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', dial: '+93', min: 9, max: 9 },
  { name: 'Albania', code: 'AL', dial: '+355', min: 8, max: 9 },
  { name: 'Algeria', code: 'DZ', dial: '+213', min: 9, max: 9 },
  { name: 'Andorra', code: 'AD', dial: '+376', min: 6, max: 8 },
  { name: 'Angola', code: 'AO', dial: '+244', min: 9, max: 9 },
  { name: 'Argentina', code: 'AR', dial: '+54', min: 10, max: 11 },
  { name: 'Armenia', code: 'AM', dial: '+374', min: 8, max: 8 },
  { name: 'Australia', code: 'AU', dial: '+61', min: 9, max: 9 },
  { name: 'Austria', code: 'AT', dial: '+43', min: 9, max: 13 },
  { name: 'Azerbaijan', code: 'AZ', dial: '+994', min: 9, max: 9 },
  { name: 'Bahrain', code: 'BH', dial: '+973', min: 8, max: 8 },
  { name: 'Bangladesh', code: 'BD', dial: '+880', min: 10, max: 10 },
  { name: 'Belarus', code: 'BY', dial: '+375', min: 9, max: 10 },
  { name: 'Belgium', code: 'BE', dial: '+32', min: 9, max: 9 },
  { name: 'Bolivia', code: 'BO', dial: '+591', min: 8, max: 8 },
  { name: 'Bosnia & Herzegovina', code: 'BA', dial: '+387', min: 8, max: 8 },
  { name: 'Brazil', code: 'BR', dial: '+55', min: 10, max: 11 },
  { name: 'Bulgaria', code: 'BG', dial: '+359', min: 8, max: 9 },
  { name: 'Cambodia', code: 'KH', dial: '+855', min: 8, max: 9 },
  { name: 'Cameroon', code: 'CM', dial: '+237', min: 9, max: 9 },
  { name: 'Canada', code: 'CA', dial: '+1', min: 10, max: 10 },
  { name: 'Chile', code: 'CL', dial: '+56', min: 9, max: 9 },
  { name: 'China', code: 'CN', dial: '+86', min: 11, max: 11 },
  { name: 'Colombia', code: 'CO', dial: '+57', min: 10, max: 10 },
  { name: 'Costa Rica', code: 'CR', dial: '+506', min: 8, max: 8 },
  { name: 'Croatia', code: 'HR', dial: '+385', min: 8, max: 9 },
  { name: 'Cuba', code: 'CU', dial: '+53', min: 8, max: 8 },
  { name: 'Cyprus', code: 'CY', dial: '+357', min: 8, max: 8 },
  { name: 'Czech Republic', code: 'CZ', dial: '+420', min: 9, max: 9 },
  { name: 'Denmark', code: 'DK', dial: '+45', min: 8, max: 8 },
  { name: 'Dominican Republic', code: 'DO', dial: '+1-809', min: 10, max: 10 },
  { name: 'Ecuador', code: 'EC', dial: '+593', min: 9, max: 9 },
  { name: 'Egypt', code: 'EG', dial: '+20', min: 10, max: 10 },
  { name: 'El Salvador', code: 'SV', dial: '+503', min: 8, max: 8 },
  { name: 'Estonia', code: 'EE', dial: '+372', min: 7, max: 8 },
  { name: 'Ethiopia', code: 'ET', dial: '+251', min: 9, max: 9 },
  { name: 'Finland', code: 'FI', dial: '+358', min: 9, max: 11 },
  { name: 'France', code: 'FR', dial: '+33', min: 9, max: 9 },
  { name: 'Georgia', code: 'GE', dial: '+995', min: 9, max: 9 },
  { name: 'Germany', code: 'DE', dial: '+49', min: 10, max: 12 },
  { name: 'Ghana', code: 'GH', dial: '+233', min: 9, max: 9 },
  { name: 'Greece', code: 'GR', dial: '+30', min: 10, max: 10 },
  { name: 'Guatemala', code: 'GT', dial: '+502', min: 8, max: 8 },
  { name: 'Honduras', code: 'HN', dial: '+504', min: 8, max: 8 },
  { name: 'Hong Kong', code: 'HK', dial: '+852', min: 8, max: 8 },
  { name: 'Hungary', code: 'HU', dial: '+36', min: 9, max: 9 },
  { name: 'Iceland', code: 'IS', dial: '+354', min: 7, max: 7 },
  { name: 'India', code: 'IN', dial: '+91', min: 10, max: 10 },
  { name: 'Indonesia', code: 'ID', dial: '+62', min: 9, max: 12 },
  { name: 'Iran', code: 'IR', dial: '+98', min: 10, max: 10 },
  { name: 'Iraq', code: 'IQ', dial: '+964', min: 10, max: 10 },
  { name: 'Ireland', code: 'IE', dial: '+353', min: 9, max: 9 },
  { name: 'Israel', code: 'IL', dial: '+972', min: 9, max: 9 },
  { name: 'Italy', code: 'IT', dial: '+39', min: 9, max: 11 },
  { name: 'Jamaica', code: 'JM', dial: '+1-876', min: 10, max: 10 },
  { name: 'Japan', code: 'JP', dial: '+81', min: 10, max: 11 },
  { name: 'Jordan', code: 'JO', dial: '+962', min: 9, max: 9 },
  { name: 'Kazakhstan', code: 'KZ', dial: '+7', min: 10, max: 10 },
  { name: 'Kenya', code: 'KE', dial: '+254', min: 9, max: 9 },
  { name: 'Kuwait', code: 'KW', dial: '+965', min: 8, max: 8 },
  { name: 'Kyrgyzstan', code: 'KG', dial: '+996', min: 9, max: 9 },
  { name: 'Laos', code: 'LA', dial: '+856', min: 9, max: 10 },
  { name: 'Latvia', code: 'LV', dial: '+371', min: 8, max: 8 },
  { name: 'Lebanon', code: 'LB', dial: '+961', min: 7, max: 8 },
  { name: 'Libya', code: 'LY', dial: '+218', min: 9, max: 9 },
  { name: 'Lithuania', code: 'LT', dial: '+370', min: 8, max: 8 },
  { name: 'Luxembourg', code: 'LU', dial: '+352', min: 9, max: 11 },
  { name: 'Malaysia', code: 'MY', dial: '+60', min: 9, max: 10 },
  { name: 'Maldives', code: 'MV', dial: '+960', min: 7, max: 7 },
  { name: 'Malta', code: 'MT', dial: '+356', min: 8, max: 8 },
  { name: 'Mauritania', code: 'MR', dial: '+222', min: 8, max: 8 },
  { name: 'Mauritius', code: 'MU', dial: '+230', min: 8, max: 8 },
  { name: 'Mexico', code: 'MX', dial: '+52', min: 10, max: 10 },
  { name: 'Moldova', code: 'MD', dial: '+373', min: 8, max: 8 },
  { name: 'Mongolia', code: 'MN', dial: '+976', min: 8, max: 8 },
  { name: 'Montenegro', code: 'ME', dial: '+382', min: 8, max: 8 },
  { name: 'Morocco', code: 'MA', dial: '+212', min: 9, max: 9 },
  { name: 'Mozambique', code: 'MZ', dial: '+258', min: 9, max: 9 },
  { name: 'Myanmar', code: 'MM', dial: '+95', min: 8, max: 10 },
  { name: 'Nepal', code: 'NP', dial: '+977', min: 10, max: 10 },
  { name: 'Netherlands', code: 'NL', dial: '+31', min: 9, max: 9 },
  { name: 'New Zealand', code: 'NZ', dial: '+64', min: 9, max: 10 },
  { name: 'Nicaragua', code: 'NI', dial: '+505', min: 8, max: 8 },
  { name: 'Nigeria', code: 'NG', dial: '+234', min: 10, max: 10 },
  { name: 'North Korea', code: 'KP', dial: '+850', min: 9, max: 10 },
  { name: 'North Macedonia', code: 'MK', dial: '+389', min: 8, max: 8 },
  { name: 'Norway', code: 'NO', dial: '+47', min: 8, max: 8 },
  { name: 'Oman', code: 'OM', dial: '+968', min: 8, max: 8 },
  { name: 'Pakistan', code: 'PK', dial: '+92', min: 10, max: 10 },
  { name: 'Palestine', code: 'PS', dial: '+970', min: 9, max: 9 },
  { name: 'Panama', code: 'PA', dial: '+507', min: 8, max: 8 },
  { name: 'Paraguay', code: 'PY', dial: '+595', min: 9, max: 9 },
  { name: 'Peru', code: 'PE', dial: '+51', min: 9, max: 9 },
  { name: 'Philippines', code: 'PH', dial: '+63', min: 10, max: 10 },
  { name: 'Poland', code: 'PL', dial: '+48', min: 9, max: 9 },
  { name: 'Portugal', code: 'PT', dial: '+351', min: 9, max: 9 },
  { name: 'Qatar', code: 'QA', dial: '+974', min: 8, max: 8 },
  { name: 'Romania', code: 'RO', dial: '+40', min: 9, max: 9 },
  { name: 'Russia', code: 'RU', dial: '+7', min: 10, max: 10 },
  { name: 'Saudi Arabia', code: 'SA', dial: '+966', min: 9, max: 9 },
  { name: 'Senegal', code: 'SN', dial: '+221', min: 9, max: 9 },
  { name: 'Serbia', code: 'RS', dial: '+381', min: 8, max: 9 },
  { name: 'Singapore', code: 'SG', dial: '+65', min: 8, max: 8 },
  { name: 'Slovakia', code: 'SK', dial: '+421', min: 9, max: 9 },
  { name: 'Slovenia', code: 'SI', dial: '+386', min: 8, max: 8 },
  { name: 'Somalia', code: 'SO', dial: '+252', min: 8, max: 9 },
  { name: 'South Africa', code: 'ZA', dial: '+27', min: 9, max: 9 },
  { name: 'South Korea', code: 'KR', dial: '+82', min: 9, max: 10 },
  { name: 'South Sudan', code: 'SS', dial: '+211', min: 9, max: 9 },
  { name: 'Spain', code: 'ES', dial: '+34', min: 9, max: 9 },
  { name: 'Sri Lanka', code: 'LK', dial: '+94', min: 9, max: 9 },
  { name: 'Sudan', code: 'SD', dial: '+249', min: 9, max: 9 },
  { name: 'Sweden', code: 'SE', dial: '+46', min: 9, max: 9 },
  { name: 'Switzerland', code: 'CH', dial: '+41', min: 9, max: 9 },
  { name: 'Syria', code: 'SY', dial: '+963', min: 9, max: 9 },
  { name: 'Taiwan', code: 'TW', dial: '+886', min: 9, max: 9 },
  { name: 'Tajikistan', code: 'TJ', dial: '+992', min: 9, max: 9 },
  { name: 'Tanzania', code: 'TZ', dial: '+255', min: 9, max: 9 },
  { name: 'Thailand', code: 'TH', dial: '+66', min: 9, max: 9 },
  { name: 'Tunisia', code: 'TN', dial: '+216', min: 8, max: 8 },
  { name: 'Turkey', code: 'TR', dial: '+90', min: 10, max: 10 },
  { name: 'Turkmenistan', code: 'TM', dial: '+993', min: 8, max: 8 },
  { name: 'Uganda', code: 'UG', dial: '+256', min: 9, max: 9 },
  { name: 'Ukraine', code: 'UA', dial: '+380', min: 9, max: 9 },
  { name: 'United Arab Emirates', code: 'AE', dial: '+971', min: 9, max: 9 },
  { name: 'United Kingdom', code: 'GB', dial: '+44', min: 10, max: 10 },
  { name: 'United States', code: 'US', dial: '+1', min: 10, max: 10 },
  { name: 'Uruguay', code: 'UY', dial: '+598', min: 9, max: 9 },
  { name: 'Uzbekistan', code: 'UZ', dial: '+998', min: 9, max: 9 },
  { name: 'Venezuela', code: 'VE', dial: '+58', min: 10, max: 10 },
  { name: 'Vietnam', code: 'VN', dial: '+84', min: 9, max: 10 },
  { name: 'Yemen', code: 'YE', dial: '+967', min: 9, max: 9 },
  { name: 'Zambia', code: 'ZM', dial: '+260', min: 9, max: 9 },
  { name: 'Zimbabwe', code: 'ZW', dial: '+263', min: 9, max: 9 },
]

export function getFlag(code) {
  const base = code.split('-')[0].toUpperCase()
  return [...base].map(c => String.fromCodePoint(0x1F1E6 + c.charCodeAt(0) - 65)).join('')
}

export const DEFAULT_COUNTRY = COUNTRIES.find(c => c.code === 'SA') || COUNTRIES[0]
